### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by rpulkka** [xTooth/ToothTiRaLabk19#1]
<h1>Vertaisarviointi</h1>

Projekti ladattu 12.2.2019 klo 11:30.
<p/>
Projektisi on oikein hyvällä mallilla ja koodi on kaiken kaikkiaan selkeää, toimivaa ja tarkkoin harkittua. Sen kuitenkin tiedät varmaan jo muutenkin, joten laitan palautteeseen pari mahdollista kehitysehdotusta.
<p/>
Koodisi vaikuttaisi sisältävän jonkin verran copy/pastea, eli vaikuttaisi siltä, että jotkut koodinpätkät toistuvat monessa luokassa. Tarkemmin sanoen, algoritmeja kuvaavissa luokissa näyttäisi toistuvan getAllowedMoves() ja makeAllowedMoves() metodit. Ovatko nämä merkittävästi keskenään erilaisia toiminnaltaaan vai olisiko mahdollista refaktoroida nuo metodit yhteiseksi algoritmiluokkien käyttöön?
<p/>
Testit vaikuttavat päällisin puolin kattavalta. En kuitenkaan saanut niitä toimimaan Netbeansin kautta, joten oletan että niiden ajaminen toimii jollain muulla tavoin tai sitten niiden kirjoittaminen on yhä vaiheessa (kuten esim. omien testieni). Voi olla, että Gradle vaikuttaa jotenkin testien ajamiseen, itse käytän Mavenia. Testien ajaminen jäi siis jumiin paikoilleen, kun yritin ajaa testit.
<p/>
Kun suoritan jonkun demo casen ohjelmalla, niin tulostuksessa on liikkeitä kuvaava taulukko, joka sisältää kirjaimia U, R, D, L, joiden merkityksen ymmärrän, mutta näiden jälkeen tulostuu taulukon jatkeeksi sarja neliötä muistuttavia merkkejä. Onko tämä tarkoituksenmukaista? 
<p/>
Seuraavana alkaisin toteuttamaan tietorakenteita. Kuten totesitkin, keon toteuttaminen tulee ainakin tarpeeseen, joten voit aloittaa vaikkapa siitä. Tietorakenteet kannattaa nyt priorisoida,  niitä ei kannata jättää ihan viime tippaan, koska niistä saa paljon kurssipisteitä.
<p/>
Kokonaisuudessaan projektisi on todella laadukas. Jos jatkat samaan malliin, tulet varmasti saamaan arvosanan 5 kurssista. Esimerkillistä työtä, oli opettavaista lukea koodiasi, koska se on selkeästi edistyneempää kuin omani. Tsemppiä kurssin loppusuoralle.

**Comment by xTooth** [comment]
Juu eli pahoittelut ohjeiden puutteesta, se taitaakin olla toinen puute. Gradle:n kautta testit toimivat ainakin molemmilla omilla koneilla. Jos projektin juuressa windows:lla  komennolla: gradlew test, ja mac:illa: gradle test linuxilla ei ole tullut testattua. Tosin gradle osaa olla ajoittain hankala, ainakin omalla koneella ei löydä javaa ilman lisäkonffausta. Jos gradle ei tahdo niin tuolta Readme.md:n Codecov badgea klikkaamalla löytyy testikattavuus "highlightattuna"! Kiitos palautteesta!
