### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by marinellalaaksonen** [xTooth/ToothTiRaLabk19#2]
projekti ladattu 22.2.2019 15:00

- Ohjelman rakenne on pääosin selkeä. HashingishTablen sisällä oleva Node luokka olisi kuitenkin ehkä selkeämpi omana luokkanaan.
- Myös muuttujien ja metodien nimet ovat kuvaavia. Metodit ovat monessa paikkassa kuitenkin hyvin pitkiä, niitä voisi pilkkoa hieman pienemmiksi (ainakin AStarSolver, Shuffler, TextBasedUI, MySolver, BFS)
- Solvereiden makeAllowedMoves(tai addAllowedMoves) metodeissa on paljon luokkien välillä toistuvaa koodia. Jos metodin jakaisi pienempiin osiin voisi toistuvat osat laittaa esimerkiksi perittävän ParentSolver-luokan alle.
- Osa algoritmeista olivat joko hyvin hitaita tai jäivät johonkin jumiin tietyillä syötteillä, tällaisia olivat ainakin BFS syötteellä 10  3  6  4, 5  9  2  8,  0  1  7 12,  13 14 11 15 (ajaminen kesti n 15 min ennen kuin keskeytin sen) ja MySolver syötteellä  1  4  6  8, 9  0  3 12, 10  2  5  7, 13 14 11 15 (java.lang.OutOfMemoryError: GC overhead limit exceeded). Saattavat toki ainakin osittain johtua myös vanhasta koneesta jolla näitä ajoin.

**Comment by xTooth** [comment]
Kiitos palautteesta ja hyvistä huomioista! Refaktorointi on vielä vähän kesken ja tuo makeAllowedMovesin muuntelu on ollut suunnitteilla jo pitkään!  Uskoisin hitauden johtuvan hashtablen törmäysten määrästä. Ylivuotoketjut voisi ehkä muuttaa puiksi tms jolloin haku olisi huomattavasti nopeampaa. Ja sitten vielä parantaa hash:äystä, törmäyksien vähentämiseksi! Tosin kyseinen ei korjaa overflow-tiloja joiden kanssa olen kamppaillut alusta asti. Niitä pitänee koittaa tutkia vielä lisää!
